version: '3.6'

services:
  l1:
    image: registry.clearlink.com/laravel-dev:alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
  db:
    image: mariadb
    environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: andrewdb
    ports:
      - "3308:3306"
    volumes:
      - /var/lib/mysql
